// This file has been autogenerated from a class added in the UI designer.

using BarcodeSDK.NET.iOS.Utils;
using ScanbotSDK.iOS;

namespace BarcodeSDK.NET.iOS.Controllers.ClassicComponents
{
    interface IBarcodeScanAndCountViewDelegate
    {
        List<SBSDKBarcodeScannerAccumulatingResult> ScannedBarcodes { get; set; }
        void UpdateScannedItems();
    }

    public partial class BarcodeScanAndCountViewController : BaseViewController, IBarcodeScanAndCountViewDelegate
    {
        SBSDKBarcodeScanAndCountViewController viewController;
        public BarcodeScanAndCountViewController(IntPtr handle) : base(handle)
        {
            PageTitle = "ScanAndCountView";
        }

        #region IBarcodeScanAndCountViewDelegate Implementation

        public List<SBSDKBarcodeScannerAccumulatingResult> ScannedBarcodes { get; set; }

        public void UpdateScannedItems()
        {
            var count = (int)ScannedBarcodes.Sum(item => item.ScanCount);
            btnBarcodeCount.Title = $"{Texts.TotalItemsScanned}: {count}";
        }

        #endregion

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            ScannedBarcodes = new List<SBSDKBarcodeScannerAccumulatingResult>();
            var barcodeConfiguration = new SBSDKBarcodeFormatCommonConfiguration
            {
                Formats = BarcodeTypes.Instance.AcceptedTypes
            };
            
            var configuration = new SBSDKBarcodeScannerConfiguration
            {
                BarcodeFormatConfigurations = [barcodeConfiguration]
            };
            
            viewController = new(parentViewController: this, containerView, configuration);
            viewController.Delegate = new BarcodeScanAndCountViewDelegate(this);
            
            // Sets the flash button to RightBarButtonItem. Updates the flash color based on flash status.
            SetFlashButton(() =>
            {
                viewController.IsFlashLightEnabled = !viewController.IsFlashLightEnabled;
                return viewController.IsFlashLightEnabled;
            });
        }

        partial void BtnShowResults_Action(UIBarButtonItem sender)
        {
            var resultController = Utilities.GetViewController<BarcodeScanAndCountResultViewController>(Texts.ClassicComponentStoryboard);
            resultController.NavigateData(ScannedBarcodes);
            NavigationController?.PushViewController(resultController, true);
        }
    }

    internal class BarcodeScanAndCountViewDelegate : SBSDKBarcodeScanAndCountViewControllerDelegate
    {
        private readonly IBarcodeScanAndCountViewDelegate scanAndCountViewDelegate;
        internal BarcodeScanAndCountViewDelegate(IBarcodeScanAndCountViewDelegate scanAndCountViewDelegate)
        {
            this.scanAndCountViewDelegate = scanAndCountViewDelegate;
        }

        public override void DidScanBarcodes(SBSDKBarcodeScanAndCountViewController controller, SBSDKBarcodeItem[] codes)
        {
            foreach (var code in codes)
            {
                var existingBarcode = scanAndCountViewDelegate.ScannedBarcodes.Find(
                    item => item.Item.Format.Equals(code.Format) 
                            && item.Item.Text == code.Text);
                
                if (existingBarcode != null)
                {
                    existingBarcode.ScanCount += 1;
                }
                else
                {
                    scanAndCountViewDelegate.ScannedBarcodes.Add(new SBSDKBarcodeScannerAccumulatingResult(code));
                }
            }
            scanAndCountViewDelegate.UpdateScannedItems();
        }

        public override UIView OverlayForBarcode(SBSDKBarcodeScanAndCountViewController controller, SBSDKBarcodeItem item)
        {
            return new UIImageView(image: UIImage.CheckmarkImage);
        }
    }
}
